window.mt = window.mt || {}; window.mt.data = {
	"assets": {
		"name": "assets",
		"contents": [
			{
				"name": "Loading",
				"contents": [
					{
						"id": 2,
						"name": "loading.png",
						"fullPath": "/Loading/loading.png",
						"key": "/preload.png",
						"width": 190,
						"height": 9,
						"frameWidth": 190,
						"frameHeight": 9,
						"frameMax": -1,
						"margin": 0,
						"spacing": 0,
						"anchorX": 0,
						"anchorY": 0,
						"fps": 10,
						"updated": 1406817917030,
						"atlas": "",
						"contents": [],
						"isClosed": true
					},
					{
						"id": 1,
						"name": "preload.png",
						"fullPath": "/Loading/preload.png",
						"key": "/loading.png",
						"width": 190,
						"height": 9,
						"frameWidth": 190,
						"frameHeight": 9,
						"frameMax": -1,
						"margin": 0,
						"spacing": 0,
						"anchorX": 0,
						"anchorY": 0,
						"fps": 10,
						"updated": 1406817915033,
						"atlas": ""
					}
				],
				"count": 0,
				"id": "33b1bd43-ce01-44bb-99df-d76cb176e950",
				"fullPath": "/Loading",
				"isClosed": true
			},
			{
				"id": "916c7e6c-c7c2-49c2-8177-692e73131d2a",
				"name": "bg.png",
				"fullPath": "/bg.png",
				"key": "/bg-1.png",
				"width": 480,
				"height": 720,
				"frameWidth": 480,
				"frameHeight": 720,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1435592786007,
				"atlas": ""
			},
			{
				"id": "acf2e01f-16ef-4447-aadc-8b360c12299a",
				"name": "character.png",
				"fullPath": "/character.png",
				"key": "/character.png",
				"width": 855,
				"height": 645,
				"frameWidth": 285,
				"frameHeight": 215,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1435496233871,
				"atlas": "",
				"physics": {
					"enable": 0
				}
			},
			{
				"id": "3db460cb-cf8d-41fb-9e6e-5d4e60e68555",
				"name": "cross.png",
				"fullPath": "/cross.png",
				"key": "/cross.png",
				"width": 80,
				"height": 86,
				"frameWidth": 80,
				"frameHeight": 86,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1435703094835,
				"atlas": ""
			},
			{
				"id": "2fdde8fa-5a7f-4400-a47f-524705f5cba0",
				"name": "hammer.png",
				"fullPath": "/hammer.png",
				"key": "/hammer.png",
				"width": 300,
				"height": 150,
				"frameWidth": 300,
				"frameHeight": 150,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1435496233876,
				"atlas": ""
			},
			{
				"id": "launcher",
				"name": "launcher.png",
				"fullPath": "/launcher.png",
				"key": "/launcher.png",
				"width": 128,
				"height": 128,
				"frameWidth": 128,
				"frameHeight": 128,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1406817915034,
				"atlas": ""
			},
			{
				"id": "8f21a4ac-9e96-4599-aa7e-cf111c7e0bf8",
				"name": "playButton.png",
				"fullPath": "/playButton.png",
				"key": "/playButton.png",
				"width": 81,
				"height": 81,
				"frameWidth": 81,
				"frameHeight": 81,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1435587277673,
				"atlas": ""
			},
			{
				"id": "7ccf1eb4-5bb9-4b3e-9a0d-5b22141abca4",
				"name": "popup.png",
				"fullPath": "/popup.png",
				"key": "/popup.png",
				"width": 283,
				"height": 249,
				"frameWidth": 283,
				"frameHeight": 249,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1435496233877,
				"atlas": ""
			},
			{
				"id": "ce3e4533-57a8-4b07-9e20-61e53eb28e6e",
				"name": "restartButton.png",
				"fullPath": "/restartButton.png",
				"key": "/restartButton.png",
				"width": 81,
				"height": 81,
				"frameWidth": 81,
				"frameHeight": 81,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1435496233879,
				"atlas": ""
			},
			{
				"id": "6b23ef07-69f0-49bf-9b0a-7f176628e8bb",
				"name": "scarecrow.png",
				"fullPath": "/scarecrow.png",
				"key": "/scarecrow.png",
				"width": 60,
				"height": 54,
				"frameWidth": 60,
				"frameHeight": 54,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1435703632594,
				"atlas": ""
			},
			{
				"id": "ec2e5dff-626b-44f7-8ee6-5d0845b3bbd1",
				"name": "stump.png",
				"fullPath": "/stump.png",
				"key": "/stump.png",
				"width": 480,
				"height": 120,
				"frameWidth": 480,
				"frameHeight": 120,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1435496233881,
				"atlas": ""
			},
			{
				"id": "1955efb6-b813-4c15-bb83-3b2f1c783237",
				"name": "timeBar.png",
				"fullPath": "/timeBar.png",
				"key": "/timeBar.png",
				"width": 100,
				"height": 15,
				"frameWidth": 100,
				"frameHeight": 15,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1435496233882,
				"atlas": ""
			},
			{
				"id": "4ae4261f-ff9a-4f33-b391-eb312fd2ac73",
				"name": "trunk.png",
				"fullPath": "/trunk.png",
				"key": "/trunk.png",
				"width": 480,
				"height": 600,
				"frameWidth": 480,
				"frameHeight": 120,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1435962424985,
				"atlas": ""
			},
			{
				"id": "7cb357f7-78d9-456a-9837-204169b233a8",
				"name": "xButton.png",
				"fullPath": "/xButton.png",
				"key": "/xButton.png",
				"width": 81,
				"height": 81,
				"frameWidth": 81,
				"frameHeight": 81,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1435600181123,
				"atlas": ""
			}
		],
		"count": 30
	},
	"objects": {
		"name": "objects",
		"contents": [
			{
				"id": "tmp1435497483408",
				"name": "popup",
				"x": 240,
				"y": 360,
				"type": 1,
				"angle": 0,
				"contents": [
					{
						"assetId": "7cb357f7-78d9-456a-9837-204169b233a8",
						"x": 1.2145839889399213e-13,
						"y": -108.3333333333331,
						"type": 0,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 0.7407407407407407,
						"scaleY": 0.7407407407407407,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": true,
						"isLocked": 0,
						"contents": [],
						"width": 60,
						"height": 60,
						"id": "tmp1435590628831",
						"name": "xButton",
						"index": -1,
						"fullPath": "/popup/xButton",
						"movies": {
							"__main": {
								"frames": [],
								"info": {
									"fps": 60
								},
								"subdata": []
							}
						},
						"assetKey": "/xButton.png"
					},
					{
						"x": 0.5263157894736837,
						"y": 15,
						"type": 2,
						"anchorX": 0.5,
						"anchorY": 0.43880048959608337,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"wordWrapWidth": 100,
						"style": {
							"fontFamily": "Nanum Brush Script",
							"fontSize": 55,
							"font": " 55px 'Nanum Brush Script'",
							"fill": "#ffffff",
							"align": "left",
							"stroke": "#000000",
							"strokeThickness": 5,
							"wordWrap": false,
							"wordWrapWidth": 100,
							"shadowOffsetX": 0,
							"shadowOffsetY": 0,
							"shadowColor": "rgba(0,0,0,0)",
							"shadowBlur": 0,
							"fontWeight": ""
						},
						"align": "left",
						"wordWrap": 0,
						"isVisible": 1,
						"isLocked": 0,
						"text": "Best:",
						"id": "tmp1435497483414",
						"name": "best",
						"index": -1,
						"fullPath": "/popup/best",
						"shadow": {},
						"physics": {
							"enable": 0
						},
						"userData": {},
						"movies": {},
						"width": 17,
						"height": 43,
						"fill": "#ffffff",
						"stroke": "#000000",
						"strokeThickness": 5
					},
					{
						"x": 0,
						"y": 55,
						"type": 2,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"wordWrapWidth": 100,
						"style": {
							"fontFamily": "Nanum Brush Script",
							"fontSize": 55,
							"font": " 55px 'Nanum Brush Script'",
							"fill": "#ffffff",
							"align": "left",
							"stroke": "#000000",
							"strokeThickness": 5,
							"wordWrap": false,
							"wordWrapWidth": 100,
							"shadowOffsetX": 0,
							"shadowOffsetY": 0,
							"shadowColor": "rgba(0,0,0,0)",
							"shadowBlur": 0,
							"fontWeight": ""
						},
						"align": "left",
						"wordWrap": 0,
						"isVisible": 1,
						"isLocked": 0,
						"text": "0",
						"id": "tmp1435497483413",
						"name": "bestValue",
						"index": -1,
						"fullPath": "/popup/bestValue",
						"shadow": {},
						"physics": {
							"enable": 0
						},
						"userData": {},
						"movies": {},
						"width": 64,
						"height": 43,
						"stroke": "#000000",
						"strokeThickness": 5,
						"fill": "#ffffff"
					},
					{
						"x": 1.0526315789473677,
						"y": -53,
						"type": 2,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"wordWrapWidth": 100,
						"style": {
							"fontFamily": "Nanum Brush Script",
							"fontSize": 55,
							"font": " 55px 'Nanum Brush Script'",
							"fill": "#ffffff",
							"align": "left",
							"stroke": "#000000",
							"strokeThickness": 5,
							"wordWrap": false,
							"wordWrapWidth": 100,
							"shadowOffsetX": 0,
							"shadowOffsetY": 0,
							"shadowColor": "rgba(0,0,0,0)",
							"shadowBlur": 0,
							"fontWeight": ""
						},
						"align": "left",
						"wordWrap": 0,
						"isVisible": 1,
						"isLocked": 0,
						"text": "Score:",
						"id": "tmp1435497483412",
						"name": "score",
						"index": -1,
						"fullPath": "/popup/score",
						"shadow": {},
						"physics": {
							"enable": 0
						},
						"userData": {},
						"movies": {},
						"width": 17,
						"height": 43,
						"fill": "#ffffff",
						"stroke": "#000000",
						"strokeThickness": 5
					},
					{
						"x": 0,
						"y": -15,
						"type": 2,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"wordWrapWidth": 100,
						"style": {
							"fontFamily": "Nanum Brush Script",
							"fontSize": 55,
							"font": " 55px 'Nanum Brush Script'",
							"fill": "#ffffff",
							"align": "left",
							"stroke": "#000000",
							"strokeThickness": 5,
							"wordWrap": false,
							"wordWrapWidth": 100,
							"shadowOffsetX": 0,
							"shadowOffsetY": 0,
							"shadowColor": "rgba(0,0,0,0)",
							"shadowBlur": 0,
							"fontWeight": ""
						},
						"align": "left",
						"wordWrap": 0,
						"isVisible": true,
						"isLocked": 0,
						"text": "0",
						"id": "tmp1435539790046",
						"name": "scoreValue",
						"index": -1,
						"fullPath": "/popup/scoreValue",
						"shadow": {},
						"physics": {
							"enable": 0
						},
						"userData": {},
						"movies": {},
						"width": 17,
						"height": 43,
						"stroke": "#000000",
						"strokeThickness": 5,
						"fill": "#ffffff"
					},
					{
						"assetId": "ce3e4533-57a8-4b07-9e20-61e53eb28e6e",
						"x": 0,
						"y": 120,
						"type": 0,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": true,
						"isLocked": 0,
						"contents": [],
						"width": 81,
						"height": 81,
						"id": "tmp1435497483410",
						"name": "restartButton",
						"index": -1,
						"fullPath": "/popup/restartButton",
						"movies": {},
						"assetKey": "/restartButton.png"
					},
					{
						"assetId": "7ccf1eb4-5bb9-4b3e-9a0d-5b22141abca4",
						"x": 0,
						"y": 0,
						"type": 0,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": true,
						"isLocked": 0,
						"contents": [],
						"width": 283,
						"height": 249,
						"id": "tmp1435497483409",
						"name": "popup",
						"index": -1,
						"fullPath": "/popup/popup",
						"isClosed": true,
						"movies": {},
						"assetKey": "/popup.png"
					}
				],
				"isVisible": false,
				"isLocked": 0,
				"isFixedToCamera": 0,
				"isClosed": true,
				"scaleX": 1,
				"scaleY": 1,
				"alpha": 1,
				"fullPath": "/popup",
				"physics": {
					"enable": 0
				},
				"userData": {},
				"movies": {
					"__main": {
						"frames": [],
						"info": {
							"fps": 60
						},
						"subdata": []
					}
				}
			},
			{
				"id": "tmp1435705491700",
				"name": "popup1",
				"x": 240,
				"y": 360,
				"type": 1,
				"angle": 0,
				"contents": [
					{
						"assetId": "7cb357f7-78d9-456a-9837-204169b233a8",
						"x": 1.2145839889399213e-13,
						"y": -108.3333333333331,
						"type": 0,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 0.7407407407407407,
						"scaleY": 0.7407407407407407,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": true,
						"isLocked": 0,
						"contents": [],
						"width": 60,
						"height": 60,
						"id": "tmp1435705491692",
						"name": "xButton",
						"index": -1,
						"fullPath": "/popup1/xButton",
						"movies": {
							"__main": {
								"frames": [],
								"info": {
									"fps": 60
								},
								"subdata": []
							}
						},
						"assetKey": "/xButton.png"
					},
					{
						"x": 1.0526315789473677,
						"y": -25,
						"type": 2,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"scaleX": 1,
						"scaleY": 1,
						"angle": -2,
						"alpha": 1,
						"wordWrapWidth": 100,
						"style": {
							"fontFamily": "Nanum Brush Script",
							"fontSize": 55,
							"font": " 55px 'Nanum Brush Script'",
							"fill": "#ffffff",
							"align": "left",
							"stroke": "#000000",
							"strokeThickness": 5,
							"wordWrap": false,
							"wordWrapWidth": 100,
							"shadowOffsetX": 0,
							"shadowOffsetY": 0,
							"shadowColor": "rgba(0,0,0,0)",
							"shadowBlur": 0,
							"fontWeight": ""
						},
						"align": "left",
						"wordWrap": 0,
						"isVisible": 1,
						"isLocked": 0,
						"text": "    New\nHigh Score!",
						"id": "tmp1435705491695",
						"name": "score",
						"index": -1,
						"fullPath": "/popup1/score",
						"shadow": {},
						"physics": {
							"enable": 0
						},
						"userData": {},
						"movies": {},
						"width": 17,
						"height": 43,
						"fill": "#ffffff",
						"stroke": "#000000",
						"strokeThickness": 5
					},
					{
						"x": 0,
						"y": 55,
						"type": 2,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"wordWrapWidth": 100,
						"style": {
							"fontFamily": "Nanum Brush Script",
							"fontSize": 55,
							"font": " 55px 'Nanum Brush Script'",
							"fill": "#ffffff",
							"align": "left",
							"stroke": "#000000",
							"strokeThickness": 5,
							"wordWrap": false,
							"wordWrapWidth": 100,
							"shadowOffsetX": 0,
							"shadowOffsetY": 0,
							"shadowColor": "rgba(0,0,0,0)",
							"shadowBlur": 0,
							"fontWeight": ""
						},
						"align": "left",
						"wordWrap": 0,
						"isVisible": true,
						"isLocked": 0,
						"text": "0",
						"id": "tmp1435705491696",
						"name": "scoreValue",
						"index": -1,
						"fullPath": "/popup1/scoreValue",
						"shadow": {},
						"physics": {
							"enable": 0
						},
						"userData": {},
						"movies": {},
						"width": 17,
						"height": 43,
						"stroke": "#000000",
						"strokeThickness": 5,
						"fill": "#ffffff"
					},
					{
						"assetId": "ce3e4533-57a8-4b07-9e20-61e53eb28e6e",
						"x": 0,
						"y": 120,
						"type": 0,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": true,
						"isLocked": 0,
						"contents": [],
						"width": 81,
						"height": 81,
						"id": "tmp1435705491697",
						"name": "restartButton",
						"index": -1,
						"fullPath": "/popup1/restartButton",
						"movies": {},
						"assetKey": "/restartButton.png"
					},
					{
						"assetId": "7ccf1eb4-5bb9-4b3e-9a0d-5b22141abca4",
						"x": 0,
						"y": 0,
						"type": 0,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": true,
						"isLocked": 0,
						"contents": [],
						"width": 283,
						"height": 249,
						"id": "tmp1435705491698",
						"name": "popup",
						"index": -1,
						"fullPath": "/popup1/popup",
						"isClosed": true,
						"movies": {},
						"assetKey": "/popup.png"
					}
				],
				"isVisible": false,
				"isLocked": 0,
				"isFixedToCamera": 0,
				"isClosed": true,
				"scaleX": 1,
				"scaleY": 1,
				"alpha": 1,
				"fullPath": "/popup1",
				"physics": {
					"enable": 0
				},
				"userData": {},
				"movies": {
					"__main": {
						"frames": [],
						"info": {
							"fps": 60
						},
						"subdata": []
					}
				},
				"index": -1
			},
			{
				"id": "tmp1435680109775",
				"name": "sound",
				"x": 0,
				"y": 0,
				"type": 1,
				"angle": 0,
				"contents": [
					{
						"assetId": "7cb357f7-78d9-456a-9837-204169b233a8",
						"x": 386.6666666666668,
						"y": 388.33333333333354,
						"type": 0,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1.2345679012345678,
						"scaleY": 1.2345679012345678,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 100,
						"height": 100,
						"id": "tmp1435680109781",
						"name": "xButton",
						"index": -1,
						"fullPath": "/sound/xButton",
						"movies": {},
						"assetKey": "/xButton.png"
					},
					{
						"assetId": "8f21a4ac-9e96-4599-aa7e-cf111c7e0bf8",
						"x": 85.00000000000004,
						"y": 388.33333333333275,
						"type": 0,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1.2345679012345678,
						"scaleY": 1.2345679012345678,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 100,
						"height": 100,
						"id": "tmp1435680109780",
						"name": "playButton",
						"index": -1,
						"fullPath": "/sound/playButton",
						"movies": {},
						"isClosed": true,
						"assetKey": "/playButton.png"
					},
					{
						"x": 390.666666666667,
						"y": 287.333333333333,
						"type": 2,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"wordWrapWidth": 100,
						"style": {
							"fontFamily": "Nanum Brush Script",
							"fontSize": 96,
							"font": " 96px 'Nanum Brush Script'",
							"fill": "#ffffff",
							"align": "left",
							"stroke": "#000000",
							"strokeThickness": 10,
							"wordWrap": false,
							"wordWrapWidth": 100,
							"shadowOffsetX": 0,
							"shadowOffsetY": 0,
							"shadowColor": "rgba(0,0,0,0)",
							"shadowBlur": 0,
							"fontWeight": ""
						},
						"align": "left",
						"wordWrap": 0,
						"isVisible": 1,
						"isLocked": 0,
						"text": "No!",
						"id": "tmp1435680109779",
						"name": "no",
						"index": -1,
						"fullPath": "/sound/no",
						"shadow": {},
						"physics": {
							"enable": 0
						},
						"userData": {},
						"movies": {},
						"stroke": "#000000",
						"strokeThickness": 10,
						"fill": "#ffffff",
						"width": 108,
						"height": 93
					},
					{
						"x": 84.00000000000001,
						"y": 287.3333333333335,
						"type": 2,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"wordWrapWidth": 100,
						"style": {
							"fontFamily": "Nanum Brush Script",
							"fontSize": 96,
							"font": " 96px 'Nanum Brush Script'",
							"fill": "#ffffff",
							"align": "left",
							"stroke": "#000000",
							"strokeThickness": 10,
							"wordWrap": false,
							"wordWrapWidth": 100,
							"shadowOffsetX": 0,
							"shadowOffsetY": 0,
							"shadowColor": "rgba(0,0,0,0)",
							"shadowBlur": 0,
							"fontWeight": ""
						},
						"align": "left",
						"wordWrap": 0,
						"isVisible": 1,
						"isLocked": 0,
						"text": "Yes!",
						"id": "tmp1435680109777",
						"name": "yes",
						"index": -1,
						"fullPath": "/sound/yes",
						"shadow": {},
						"physics": {
							"enable": 0
						},
						"userData": {},
						"movies": {},
						"stroke": "#000000",
						"strokeThickness": 10,
						"fill": "#ffffff",
						"width": 145,
						"height": 93
					},
					{
						"x": 240,
						"y": 175,
						"type": 2,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"wordWrapWidth": 100,
						"style": {
							"fontFamily": "Nanum Brush Script",
							"fontSize": 96,
							"font": " 96px 'Nanum Brush Script'",
							"fill": "#ffffff",
							"align": "left",
							"stroke": "#000000",
							"strokeThickness": 10,
							"wordWrap": false,
							"wordWrapWidth": 100,
							"shadowOffsetX": 0,
							"shadowOffsetY": 0,
							"shadowColor": "rgba(0,0,0,0)",
							"shadowBlur": 0,
							"fontWeight": ""
						},
						"align": "left",
						"wordWrap": 0,
						"isVisible": true,
						"isLocked": 0,
						"text": "Sound?",
						"id": "tmp1435680109776",
						"name": "sound",
						"index": -1,
						"fullPath": "/sound/sound",
						"shadow": {},
						"physics": {
							"enable": 0
						},
						"userData": {},
						"movies": {},
						"fill": "#ffffff",
						"stroke": "#000000",
						"strokeThickness": 10,
						"width": 223,
						"height": 93
					}
				],
				"isVisible": false,
				"isLocked": 0,
				"isFixedToCamera": 0,
				"isClosed": true,
				"scaleX": 1,
				"scaleY": 1,
				"alpha": 1,
				"fullPath": "/sound",
				"physics": {
					"enable": 0
				},
				"userData": {},
				"movies": {
					"__main": {
						"frames": [],
						"info": {
							"fps": 60
						},
						"subdata": []
					}
				}
			},
			{
				"id": "tmp1435536137229",
				"name": "ui",
				"x": 0,
				"y": 0,
				"type": 1,
				"angle": 0,
				"contents": [
					{
						"x": 349.9772727272728,
						"y": 70.5909090909091,
						"type": 2,
						"anchorX": 0,
						"anchorY": 0,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"wordWrapWidth": 100,
						"style": {
							"fontFamily": "Nanum Brush Script",
							"fontSize": 55,
							"font": " 55px 'Nanum Brush Script'",
							"fill": "#ffffff",
							"align": "left",
							"stroke": "#000000",
							"strokeThickness": 5,
							"wordWrap": false,
							"wordWrapWidth": 100,
							"shadowOffsetX": 0,
							"shadowOffsetY": 0,
							"shadowColor": "rgba(0,0,0,0)",
							"shadowBlur": 0,
							"fontWeight": ""
						},
						"align": "left",
						"wordWrap": 0,
						"isVisible": 1,
						"isLocked": 0,
						"text": "0",
						"id": "tmp1435536137237",
						"name": "scoreValue",
						"index": -1,
						"fullPath": "/ui/scoreValue",
						"shadow": {},
						"physics": {
							"enable": 0
						},
						"userData": {},
						"movies": {
							"__main": {
								"frames": [],
								"info": {
									"fps": 60
								},
								"subdata": []
							}
						},
						"stroke": "#000000",
						"strokeThickness": 5,
						"fill": "#ffffff"
					},
					{
						"x": 348.97727272727246,
						"y": 33.27272727272728,
						"type": 2,
						"anchorX": 0,
						"anchorY": 0,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"wordWrapWidth": 100,
						"style": {
							"fontFamily": "Nanum Brush Script",
							"fontSize": 55,
							"font": " 55px 'Nanum Brush Script'",
							"fill": "#ffffff",
							"align": "left",
							"stroke": "#000000",
							"strokeThickness": 5,
							"wordWrap": false,
							"wordWrapWidth": 100,
							"shadowOffsetX": 0,
							"shadowOffsetY": 0,
							"shadowColor": "rgba(0,0,0,0)",
							"shadowBlur": 0,
							"fontWeight": ""
						},
						"align": "left",
						"wordWrap": 0,
						"isVisible": 1,
						"isLocked": 0,
						"text": "Score:",
						"id": "tmp1435536137231",
						"name": "score",
						"index": -1,
						"fullPath": "/ui/score",
						"shadow": {},
						"physics": {
							"enable": 0
						},
						"userData": {},
						"movies": {},
						"stroke": "#000000",
						"strokeThickness": 5,
						"fill": "#ffffff"
					},
					{
						"assetId": "1955efb6-b813-4c15-bb83-3b2f1c783237",
						"x": 348.42857142857133,
						"y": 18,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 100,
						"height": 15,
						"id": "tmp1435536137230",
						"name": "timeBar",
						"index": -1,
						"fullPath": "/ui/timeBar",
						"movies": {},
						"assetKey": "/timeBar.png"
					}
				],
				"isVisible": false,
				"isLocked": 0,
				"isFixedToCamera": 0,
				"isClosed": true,
				"scaleX": 1,
				"scaleY": 1,
				"alpha": 1,
				"fullPath": "/ui",
				"physics": {
					"enable": 0
				},
				"userData": {},
				"movies": {
					"__main": {
						"frames": [],
						"info": {
							"fps": 60
						},
						"subdata": []
					}
				}
			},
			{
				"id": "tmp1435581754840",
				"name": "menu",
				"x": 0,
				"y": 0,
				"type": 1,
				"angle": 0,
				"contents": [
					{
						"x": 414.3333333333335,
						"y": 672.9999999999993,
						"type": 2,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"wordWrapWidth": 100,
						"style": {
							"fontFamily": "Nanum Brush Script",
							"fontSize": 48,
							"font": " 48px 'Nanum Brush Script'",
							"fill": "#ffffff",
							"align": "left",
							"stroke": "#000000",
							"strokeThickness": 10,
							"wordWrap": false,
							"wordWrapWidth": 100,
							"shadowOffsetX": 0,
							"shadowOffsetY": 0,
							"shadowColor": "rgba(0,0,0,0)",
							"shadowBlur": 0,
							"fontWeight": ""
						},
						"align": "left",
						"wordWrap": 0,
						"isVisible": 1,
						"isLocked": 0,
						"text": "Sound?",
						"id": "tmp1435680109782",
						"name": "soundo",
						"index": -1,
						"fullPath": "/menu/soundo",
						"shadow": {},
						"physics": {
							"enable": 0
						},
						"userData": {},
						"movies": {},
						"fill": "#ffffff",
						"stroke": "#000000",
						"strokeThickness": 10,
						"width": 116,
						"height": 55
					},
					{
						"x": 240,
						"y": 390,
						"type": 2,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"wordWrapWidth": 100,
						"style": {
							"fontFamily": "Nanum Brush Script",
							"fontSize": 72,
							"font": " 72px 'Nanum Brush Script'",
							"fill": "#ffffff",
							"align": "left",
							"stroke": "#000000",
							"strokeThickness": 5,
							"wordWrap": false,
							"wordWrapWidth": 100,
							"shadowOffsetX": 0,
							"shadowOffsetY": 0,
							"shadowColor": "rgba(0,0,0,0)",
							"shadowBlur": 0,
							"fontWeight": ""
						},
						"align": "left",
						"wordWrap": 0,
						"isVisible": 1,
						"isLocked": 0,
						"text": "0",
						"id": "tmp1435610638688",
						"name": "bestValue",
						"index": -1,
						"fullPath": "/menu/bestValue",
						"shadow": {},
						"physics": {
							"enable": 0
						},
						"userData": {},
						"movies": {},
						"width": 17,
						"height": 43,
						"fill": "#ffffff",
						"stroke": "#000000",
						"strokeThickness": 5
					},
					{
						"x": 240,
						"y": 320,
						"type": 2,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"wordWrapWidth": 100,
						"style": {
							"fontFamily": "Nanum Brush Script",
							"fontSize": 55,
							"font": " 55px 'Nanum Brush Script'",
							"fill": "#ffffff",
							"align": "left",
							"stroke": "#000000",
							"strokeThickness": 5,
							"wordWrap": false,
							"wordWrapWidth": 100,
							"shadowOffsetX": 0,
							"shadowOffsetY": 0,
							"shadowColor": "rgba(0,0,0,0)",
							"shadowBlur": 0,
							"fontWeight": ""
						},
						"align": "left",
						"wordWrap": 0,
						"isVisible": 1,
						"isLocked": 0,
						"text": "High Score:",
						"id": "tmp1435610638687",
						"name": "best",
						"index": -1,
						"fullPath": "/menu/best",
						"shadow": {},
						"physics": {
							"enable": 0
						},
						"userData": {},
						"movies": {},
						"width": 167,
						"height": 43,
						"stroke": "#000000",
						"strokeThickness": 5,
						"fill": "#ffffff"
					},
					{
						"x": 240,
						"y": 130,
						"type": 2,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"wordWrapWidth": 100,
						"style": {
							"fontFamily": "Nanum Brush Script",
							"fontSize": 96,
							"font": " 96px 'Nanum Brush Script'",
							"fill": "#000000",
							"align": "left",
							"stroke": "#ffffff",
							"strokeThickness": 10,
							"wordWrap": false,
							"wordWrapWidth": 100,
							"shadowOffsetX": 0,
							"shadowOffsetY": 0,
							"shadowColor": "rgba(0,0,0,0)",
							"shadowBlur": 0,
							"fontWeight": ""
						},
						"align": "left",
						"wordWrap": 0,
						"isVisible": 1,
						"isLocked": 0,
						"text": "Lumber Ghoul!",
						"id": "tmp1435610638686",
						"name": "logo",
						"index": -1,
						"fullPath": "/menu/logo",
						"shadow": {},
						"physics": {
							"enable": 0
						},
						"userData": {},
						"movies": {},
						"fill": "#000000",
						"stroke": "#ffffff",
						"strokeThickness": 10,
						"width": 221,
						"height": 53
					},
					{
						"assetId": "8f21a4ac-9e96-4599-aa7e-cf111c7e0bf8",
						"x": 240,
						"y": 480,
						"type": 0,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 81,
						"height": 81,
						"id": "tmp1435582721662",
						"name": "playButton",
						"index": -1,
						"fullPath": "/menu/playButton",
						"movies": {},
						"assetKey": "/playButton.png"
					},
					{
						"assetId": "7ccf1eb4-5bb9-4b3e-9a0d-5b22141abca4",
						"x": 240,
						"y": 360,
						"type": 0,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": true,
						"isLocked": 0,
						"contents": [],
						"width": 283,
						"height": 249,
						"id": "tmp1435581754841",
						"name": "popup",
						"index": -1,
						"fullPath": "/menu/popup",
						"movies": {},
						"isClosed": true,
						"assetKey": "/popup.png"
					}
				],
				"isVisible": false,
				"isLocked": 0,
				"isFixedToCamera": 0,
				"isClosed": true,
				"scaleX": 1,
				"scaleY": 1,
				"alpha": 1,
				"fullPath": "/menu",
				"physics": {
					"enable": 0
				},
				"userData": {},
				"movies": {
					"__main": {
						"frames": [],
						"info": {
							"fps": 60
						},
						"subdata": []
					}
				}
			},
			{
				"assetId": "acf2e01f-16ef-4447-aadc-8b360c12299a",
				"x": 239.99999999999932,
				"y": 411,
				"type": 0,
				"anchorX": 0.15421670742184534,
				"anchorY": 0.09882843659779332,
				"userData": {},
				"physics": {
					"enable": 0
				},
				"scaleX": 0.9970451232921174,
				"scaleY": 1,
				"angle": 0.38452965958450785,
				"alpha": 1,
				"frame": 0,
				"isVisible": true,
				"isLocked": 0,
				"contents": [],
				"width": 284.15786013825345,
				"height": 215,
				"id": "tmp1435497483406",
				"name": "character",
				"index": -1,
				"fullPath": "/character",
				"movies": {
					"__main": {
						"frames": [],
						"info": {
							"fps": 60
						},
						"subdata": []
					}
				},
				"isClosed": true,
				"assetKey": "/character.png"
			},
			{
				"id": "tmp1435961416517",
				"name": "trunk",
				"x": 0,
				"y": 0,
				"type": 1,
				"angle": 0,
				"contents": [
					{
						"assetId": "4ae4261f-ff9a-4f33-b391-eb312fd2ac73",
						"x": 0,
						"y": 0,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 480,
						"height": 120,
						"frameName": "",
						"id": "tmp1435961416536",
						"name": "trunk5",
						"index": -1,
						"fullPath": "/trunk/trunk5",
						"assetKey": "/trunk.png"
					},
					{
						"assetId": "4ae4261f-ff9a-4f33-b391-eb312fd2ac73",
						"x": 0,
						"y": 120,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 2,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 480,
						"height": 120,
						"frameName": "",
						"id": "tmp1435961416535",
						"name": "trunk4",
						"index": -1,
						"fullPath": "/trunk/trunk4",
						"assetKey": "/trunk.png"
					},
					{
						"assetId": "4ae4261f-ff9a-4f33-b391-eb312fd2ac73",
						"x": 0,
						"y": 240,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 1,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 480,
						"height": 120,
						"frameName": "",
						"id": "tmp1435961416534",
						"name": "trunk3",
						"index": -1,
						"fullPath": "/trunk/trunk3",
						"assetKey": "/trunk.png"
					},
					{
						"assetId": "4ae4261f-ff9a-4f33-b391-eb312fd2ac73",
						"x": 0,
						"y": 360,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 3,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 480,
						"height": 120,
						"frameName": "",
						"id": "tmp1435961416533",
						"name": "trunk2",
						"index": -1,
						"fullPath": "/trunk/trunk2",
						"assetKey": "/trunk.png"
					},
					{
						"assetId": "4ae4261f-ff9a-4f33-b391-eb312fd2ac73",
						"x": 0,
						"y": 480,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 4,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 480,
						"height": 120,
						"frameName": "",
						"id": "tmp1435961416532",
						"name": "trunk1",
						"index": -1,
						"fullPath": "/trunk/trunk1",
						"assetKey": "/trunk.png"
					}
				],
				"isVisible": 1,
				"isLocked": 0,
				"isFixedToCamera": 0,
				"isClosed": false,
				"scaleX": 1,
				"scaleY": 1,
				"alpha": 1,
				"fullPath": "/trunk",
				"physics": {
					"enable": 0
				},
				"userData": {},
				"movies": {
					"__main": {
						"frames": [],
						"info": {
							"fps": 60
						},
						"subdata": []
					}
				}
			},
			{
				"id": "tmp1435495834712",
				"name": "bg",
				"x": 0,
				"y": 0,
				"type": 1,
				"angle": 0,
				"contents": [
					{
						"assetId": "6b23ef07-69f0-49bf-9b0a-7f176628e8bb",
						"x": 421.66666666666663,
						"y": 578.3333333333333,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 60,
						"height": 54,
						"id": "tmp1435701899926",
						"name": "scarecrow",
						"index": -1,
						"fullPath": "/bg/scarecrow",
						"assetKey": "/scarecrow.png"
					},
					{
						"assetId": "3db460cb-cf8d-41fb-9e6e-5d4e60e68555",
						"x": 0,
						"y": 561.6666666666666,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 80,
						"height": 86,
						"id": "tmp1435701899925",
						"name": "cross",
						"index": -1,
						"fullPath": "/bg/cross",
						"assetKey": "/cross.png"
					},
					{
						"assetId": "ec2e5dff-626b-44f7-8ee6-5d0845b3bbd1",
						"x": 0,
						"y": 600,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 480,
						"height": 120,
						"id": "tmp1435495834711",
						"name": "stump",
						"index": -1,
						"fullPath": "/bg/stump",
						"movies": {
							"__main": {
								"frames": [],
								"info": {
									"fps": 60
								},
								"subdata": []
							}
						},
						"isClosed": true,
						"assetKey": "/stump.png"
					},
					{
						"assetId": "916c7e6c-c7c2-49c2-8177-692e73131d2a",
						"x": 0,
						"y": 0,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"userData": {},
						"physics": {
							"enable": 0
						},
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"contents": [],
						"width": 480,
						"height": 720,
						"id": "tmp1435590628829",
						"name": "bg",
						"index": -1,
						"fullPath": "/bg/bg",
						"movies": {},
						"assetKey": "/bg-1.png"
					}
				],
				"isVisible": true,
				"isLocked": 0,
				"isFixedToCamera": 0,
				"isClosed": true,
				"scaleX": 1,
				"scaleY": 1,
				"alpha": 1,
				"fullPath": "/bg",
				"physics": {
					"enable": 0
				},
				"userData": {},
				"movies": {
					"__main": {
						"frames": [],
						"info": {
							"fps": 60
						},
						"subdata": []
					}
				}
			},
			{
				"id": "tmp1406818026618",
				"name": "Loading",
				"x": 0,
				"y": 0,
				"angle": 0,
				"contents": [
					{
						"x": 240,
						"y": 445,
						"type": 2,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"wordWrapWidth": 100,
						"style": {
							"fontFamily": "Nanum Brush Script",
							"fontSize": 65,
							"font": " 65px 'Nanum Brush Script'",
							"fill": "#ffffff",
							"align": "left",
							"stroke": "#000000",
							"strokeThickness": 10,
							"wordWrap": false,
							"wordWrapWidth": 100,
							"shadowOffsetX": 0,
							"shadowOffsetY": 0,
							"shadowColor": "rgba(0,0,0,0)",
							"shadowBlur": 0,
							"fontWeight": ""
						},
						"align": "left",
						"wordWrap": 0,
						"isVisible": true,
						"isLocked": 0,
						"text": "Loading...",
						"id": "tmp1435610638689",
						"name": "loading",
						"index": -1,
						"fullPath": "/Loading/loading",
						"shadow": {},
						"physics": {
							"enable": 0
						},
						"userData": {},
						"movies": {
							"__main": {
								"frames": [],
								"info": {
									"fps": 60
								},
								"subdata": []
							}
						},
						"stroke": "#000000",
						"strokeThickness": 10,
						"fill": "#ffffff",
						"width": 214,
						"height": 79
					},
					{
						"assetId": 1,
						"x": 240,
						"y": 490,
						"type": 0,
						"anchorX": 0.5,
						"anchorY": 0.5,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"width": 190,
						"height": 9,
						"id": "tmp1406818026616",
						"name": "preload",
						"fullPath": "/Loading/preload",
						"contents": [],
						"physics": {
							"enable": 0
						},
						"userData": {},
						"movies": {},
						"isClosed": true,
						"assetKey": "/loading.png"
					},
					{
						"id": "tmp1435961416543",
						"name": "trunk1",
						"x": 0,
						"y": 0,
						"type": 1,
						"angle": 0,
						"contents": [
							{
								"assetId": "4ae4261f-ff9a-4f33-b391-eb312fd2ac73",
								"x": 0,
								"y": 0,
								"type": 0,
								"anchorX": 0,
								"anchorY": 0,
								"userData": {},
								"physics": {
									"enable": 0
								},
								"scaleX": 1,
								"scaleY": 1,
								"angle": 0,
								"alpha": 1,
								"frame": 0,
								"isVisible": 1,
								"isLocked": 0,
								"contents": [],
								"width": 480,
								"height": 120,
								"frameName": "",
								"id": "tmp1435961416537",
								"name": "trunk5",
								"index": -1,
								"fullPath": "/Loading/trunk1/trunk5",
								"assetKey": "/trunk.png"
							},
							{
								"assetId": "4ae4261f-ff9a-4f33-b391-eb312fd2ac73",
								"x": 0,
								"y": 120,
								"type": 0,
								"anchorX": 0,
								"anchorY": 0,
								"userData": {},
								"physics": {
									"enable": 0
								},
								"scaleX": 1,
								"scaleY": 1,
								"angle": 0,
								"alpha": 1,
								"frame": 2,
								"isVisible": 1,
								"isLocked": 0,
								"contents": [],
								"width": 480,
								"height": 120,
								"frameName": "",
								"id": "tmp1435961416538",
								"name": "trunk4",
								"index": -1,
								"fullPath": "/Loading/trunk1/trunk4",
								"assetKey": "/trunk.png"
							},
							{
								"assetId": "4ae4261f-ff9a-4f33-b391-eb312fd2ac73",
								"x": 0,
								"y": 240,
								"type": 0,
								"anchorX": 0,
								"anchorY": 0,
								"userData": {},
								"physics": {
									"enable": 0
								},
								"scaleX": 1,
								"scaleY": 1,
								"angle": 0,
								"alpha": 1,
								"frame": 1,
								"isVisible": 1,
								"isLocked": 0,
								"contents": [],
								"width": 480,
								"height": 120,
								"frameName": "",
								"id": "tmp1435961416539",
								"name": "trunk3",
								"index": -1,
								"fullPath": "/Loading/trunk1/trunk3",
								"assetKey": "/trunk.png"
							},
							{
								"assetId": "4ae4261f-ff9a-4f33-b391-eb312fd2ac73",
								"x": 0,
								"y": 360,
								"type": 0,
								"anchorX": 0,
								"anchorY": 0,
								"userData": {},
								"physics": {
									"enable": 0
								},
								"scaleX": 1,
								"scaleY": 1,
								"angle": 0,
								"alpha": 1,
								"frame": 3,
								"isVisible": 1,
								"isLocked": 0,
								"contents": [],
								"width": 480,
								"height": 120,
								"frameName": "",
								"id": "tmp1435961416540",
								"name": "trunk2",
								"index": -1,
								"fullPath": "/Loading/trunk1/trunk2",
								"assetKey": "/trunk.png"
							},
							{
								"assetId": "4ae4261f-ff9a-4f33-b391-eb312fd2ac73",
								"x": 0,
								"y": 480,
								"type": 0,
								"anchorX": 0,
								"anchorY": 0,
								"userData": {},
								"physics": {
									"enable": 0
								},
								"scaleX": 1,
								"scaleY": 1,
								"angle": 0,
								"alpha": 1,
								"frame": 4,
								"isVisible": 1,
								"isLocked": 0,
								"contents": [],
								"width": 480,
								"height": 120,
								"frameName": "",
								"id": "tmp1435961416541",
								"name": "trunk1",
								"index": -1,
								"fullPath": "/Loading/trunk1/trunk1",
								"assetKey": "/trunk.png"
							}
						],
						"isVisible": 1,
						"isLocked": 0,
						"isFixedToCamera": 0,
						"isClosed": true,
						"scaleX": 1,
						"scaleY": 1,
						"alpha": 1,
						"fullPath": "/Loading/trunk1",
						"physics": {
							"enable": 0
						},
						"userData": {},
						"movies": {
							"__main": {
								"frames": [],
								"info": {
									"fps": 60
								},
								"subdata": []
							}
						},
						"index": -1
					},
					{
						"id": "tmp1435701899938",
						"name": "bg",
						"x": 0,
						"y": 0,
						"type": 1,
						"angle": 0,
						"contents": [
							{
								"assetId": "6b23ef07-69f0-49bf-9b0a-7f176628e8bb",
								"x": 421.66666666666663,
								"y": 578.3333333333333,
								"type": 0,
								"anchorX": 0,
								"anchorY": 0,
								"userData": {},
								"physics": {},
								"scaleX": 1,
								"scaleY": 1,
								"angle": 0,
								"alpha": 1,
								"frame": 0,
								"isVisible": 1,
								"isLocked": 0,
								"contents": [],
								"width": 60,
								"height": 54,
								"id": "tmp1435701899933",
								"name": "scarecrow",
								"index": -1,
								"fullPath": "/Loading/bg/scarecrow",
								"assetKey": "/scarecrow.png"
							},
							{
								"assetId": "3db460cb-cf8d-41fb-9e6e-5d4e60e68555",
								"x": 0,
								"y": 561.6666666666666,
								"type": 0,
								"anchorX": 0,
								"anchorY": 0,
								"userData": {},
								"physics": {},
								"scaleX": 1,
								"scaleY": 1,
								"angle": 0,
								"alpha": 1,
								"frame": 0,
								"isVisible": 1,
								"isLocked": 0,
								"contents": [],
								"width": 80,
								"height": 86,
								"id": "tmp1435701899934",
								"name": "cross",
								"index": -1,
								"fullPath": "/Loading/bg/cross",
								"assetKey": "/cross.png"
							},
							{
								"assetId": "ec2e5dff-626b-44f7-8ee6-5d0845b3bbd1",
								"x": 0,
								"y": 600,
								"type": 0,
								"anchorX": 0,
								"anchorY": 0,
								"userData": {},
								"physics": {
									"enable": 0
								},
								"scaleX": 1,
								"scaleY": 1,
								"angle": 0,
								"alpha": 1,
								"frame": 0,
								"isVisible": 1,
								"isLocked": 0,
								"contents": [],
								"width": 480,
								"height": 120,
								"id": "tmp1435701899935",
								"name": "stump",
								"index": -1,
								"fullPath": "/Loading/bg/stump",
								"movies": {
									"__main": {
										"frames": [],
										"info": {
											"fps": 60
										},
										"subdata": []
									}
								},
								"isClosed": true,
								"assetKey": "/stump.png"
							},
							{
								"assetId": "916c7e6c-c7c2-49c2-8177-692e73131d2a",
								"x": 0,
								"y": 0,
								"type": 0,
								"anchorX": 0,
								"anchorY": 0,
								"userData": {},
								"physics": {
									"enable": 0
								},
								"scaleX": 1,
								"scaleY": 1,
								"angle": 0,
								"alpha": 1,
								"frame": 0,
								"isVisible": 1,
								"isLocked": 0,
								"contents": [],
								"width": 480,
								"height": 720,
								"id": "tmp1435701899936",
								"name": "bg",
								"index": -1,
								"fullPath": "/Loading/bg/bg",
								"movies": {},
								"assetKey": "/bg-1.png"
							}
						],
						"isVisible": true,
						"isLocked": 0,
						"isFixedToCamera": 0,
						"isClosed": true,
						"scaleX": 1,
						"scaleY": 1,
						"alpha": 1,
						"fullPath": "/Loading/bg",
						"physics": {
							"enable": 0
						},
						"userData": {},
						"movies": {
							"__main": {
								"frames": [],
								"info": {
									"fps": 60
								},
								"subdata": []
							}
						},
						"index": -1
					}
				],
				"isVisible": false,
				"isLocked": true,
				"isFixedToCamera": 0,
				"fullPath": "/Loading",
				"isClosed": false,
				"movies": {
					"__main": {
						"frames": [],
						"info": {
							"fps": 60
						},
						"subdata": []
					}
				},
				"type": 1,
				"alpha": 1,
				"physics": {
					"enable": 0
				},
				"userData": {}
			}
		],
		"count": 0
	},
	"map": {
		"cameraX": -325,
		"cameraY": -210.50000000000006,
		"worldWidth": 480,
		"worldHeight": 720,
		"viewportWidth": 480,
		"viewportHeight": 720,
		"scaleMode": "SHOW_ALL",
		"gridX": 160,
		"gridY": 120,
		"gridOffsetX": 0,
		"gridOffsetY": 0,
		"showGrid": 1,
		"gridOpacity": 0.3,
		"backgroundColor": "#222222",
		"movieInfo": {
			"fps": 60,
			"lastFrame": 60
		},
		"pixelPerfectPicking": 1,
		"physics": {
			"enable": 0
		}
	}
};
